#!/bin/bash
#SBATCH --time=20:00:00
#SBATCH --account=def-gowens
#SBATCH --ntasks=4
#SBATCH --mem-per-cpu=10G

# BUSCO with contig file (fasta)
# BUSCO requires you to work in a Python Wheel environment.
# So first, you create a Python environment in your workspace.
# you're suggested to work in a new screen so that all softwares are properly loaded.
module load StdEnv/2020 gcc python augustus hmmer blast+ metaeuk prodigal r
virtualenv busco_env
source busco_env/bin/activate
pip install biopython pandas busco --no-index

# If working properly, you will be directed to a python environment like this:
## (busco_env) [kaedeh@cdr767 strawberry_genome]$

# You're good to proceed.
# Run BUSCO job:
busco --offline \
--in /home/kaedeh/scratch/strawberry_genome/results/SRR11606867.asm.bp.p_ctg.fa \
--out SRR11606867.BUSCO_output \
--lineage_dataset /home/kaedeh/scratch/strawberry_genome/reference_data/eudicots_odb10 \
--mode genome

# Once job is done, this will generate a directory named "SRR11606867.busco_output"
# in the directory you're calling this command in.
