#!/bin/bash

##Quality check for sequenced reads mapped to reference genome

# 1) Align to reference genome using minimap2
export PATH=$PATH:/home/kaedeh/projects/def-gowens/kaedeh/cranberry_genome/bin2/anchorwave/minimap2/
export PATH=$PATH:/home/kaedeh/projects/def-gowens/kaedeh/cranberry_genome/bin
minimap2 -ax map-ont V_macrocarpon_Stevens_v1_refgenome_chr.fa Lingonberry_qiagen_01_Mar04_2022.fastq.gz > Lingonberry_qiagen_01_Mar04_2022_V_macrocarpon_Stevens_v1_aln.sam

# 2) Check quality of alignment with samtools stats and visualize with bamstats
module load samtools
module load gnuplot
samtools stats Lingonberry_Takara_01_Apr_01_2022_Vmac_Vvitis_combined_aln.sam > samtools_stats_Lingonberry_Takara_01_Apr_01_2022_Vmac_Vvitis_combined_aln_summary
plot-bamstats -p samtools_plot-bamstats_Lingonberry_qiagen_01_Takara_01_combined_Vvitis_chloroplast_aln samtools_stats_Lingonberry_qiagen_01_Takara_01_combined_Vvitis_chloroplast_aln_summary
#import output PNG or html to your local computer and open

# 3) Align to reference genome using minimap2
minimap2 -ax map-ont LC521969.1_V_vitis-idaea_chloroplast.fasta /home/kaedeh/scratch/Lingonberry/output/guppy/Lingonberry_qiagen_01_Takara_01_combined.fastq.gz > Lingonberry_qiagen_01_Takara_01_combined_Vvitis_chloroplast_aln.sam
## Make sure to allocate enough resource for this job.

# 4) convert SAM to BAM
samtools sort -O bam Lingonberry_Takara_01_Apr_01_2022_Vmac_Vvitis_combined_aln.sam > Lingonberry_Takara_01_Apr_01_2022_Vmac_Vvitis_combined_aln.sort.bam
samtools index Lingonberry_Takara_01_Apr_01_2022_Vmac_Vvitis_combined_aln.sort.bam
samtools depth -r LC521969.1 Lingonberry_Takara_01_Apr_01_2022_Vmac_Vvitis_combined_aln.sort.bam | less -S # tells you the depth at $chr name specified by -r.

# 5) Viualize coverage and alignment in IGV
## import Genome: Reference genome.fasta (as the background)
## import BAM file (make sure bam.fai is in the working directory you're importing from)
