#!/bin/bash
###### Basic BLAST analysis #########

module load bedtools
module load samtools
module load StdEnv/2020 gcc/9.3.0 blast+/2.14.0

###------ BLASTn centromeric repeats to lingonberry contigs ------### 
centromeric_repeats=/~/reference_data/V_corymbosum_Draper_v1.0_centromeric_regions.fa
GST_gene=poplar_glutathione_transferase_genes.fa
RedCandy_genome_scaffold=/~/Lingonberry_RedCandy_asm_7.2.ragtag.scaffold.fasta
RedCandy_genome_contig=/~/Lingonberry_RedCandy_asm_7.2_purge_haplotig_curated.fasta
RedCandy_proteins=/~/Vvitis-idaea_ssp_vitis-idaea_var_RedCandy_genome_proteins.faa

makeblastdb -in $centromeric_repeats -dbtype nucl
blastn -query $RedCandy_genome_scaffold -db $centromeric_repeats -out RedCandy_centromeric_repeats_blast.txt -outfmt 6

###------ BLASTn or BLASTp phenolic compound genes from blueberry genome to lingonberry genome/contigs ------###

#------GST (glutathione transferase gene)------#
makeblastdb -in $GST_gene -dbtype nucl
blastn -query $RedCandy_genome_contig -db blueberry_GST_genes.fasta -out RedCandy_GST_nucl_blast.txt -outfmt 6 #No hits... 
makeblastdb -in glutathione_transferase.faa -out glutathione_transferase -dbtype prot
blastp -query $Vcorymbosum_anno_proteins -db glutathione_transferase -out glutathione_transferase_gene_blastp_V_corymbosum_Draper_v1.0.txt #No hits... 

##from the output file, I chose the sequences with >95% alignment score and >220/233 alignment length 
cat glutathione_transferase_gene_blastp_V_corymbosum_Draper_v1.0.txt | awk '{if ($4>=200){print}}' | awk '{if ($3>=90){print}}' > glutathione_transferase_gene_blastp_top_hits_V_corymbosum_Draper_v1.0.txt
mkdir orthologous_strings_GST_N1
for enzyme in `cat enzyme_names_GST.txt`;
do
       for gene in `cat stringnames_${enzyme}.txt`;
       do
              cat N1.tsv | grep "$gene" > orthologous_strings_GST_N1/${enzyme}_${gene}.gff3
       done
done
for enzyme in `cat ../enzyme_names_GST.txt`;
do
       cat ${enzyme}_* > ${enzyme}_orthologs.txt
done
for enzyme in `cat ../enzyme_names_GST.txt`;
do
       cat ${enzyme}_orthologs.txt | cut -f 7 | sed 's/\./    /2' | cut -f 1 | sort | uniq > lingonberry_${enzyme}_orthologs.txt;
done

##This didn't find any orthologous genes in lingonberry annotation... even though there are orthologs in all the other Vaccinium species I've included. 

##what if we BLASLT on our assembled contigs instead of proteins? 
##BLASTn found hits on our contigs (partially annotated), which did not was not recognized as a complete coding gene in our annotation. 
#For this I downloaded GST gene in nucleotides.fasta from NCBI Genebank 
makeblastdb -in blueberry_GST_genes.fasta -dbtype nucl
blastn -query $RedCandy_genome_contig -db blueberry_GST_genes.fasta -out RedCandy_GST_nucl_blast.txt -outfmt 6


#------blueberry proteins to orthologous lingonberry genes------#
Vcorymbosum_anno_proteins=/~/reference_data/V_corymbosum_Draper_v1.0-proteins-nameTruncated.fasta
makeblastdb -in V_corymbosum_Draper_v1.0_flavonoid_proteins.fasta -dbtype prot
blastp -query $RedCandy_proteins -db V_corymbosum_Draper_v1.0_flavonoid_proteins.fasta -out RedCandy_Vcorymbosum_flavonoid_genes_prot_blast.txt -outfmt 6
blastp -query $RedCandy_proteins -db V_corymbosum_Draper_v1.0_flavonoid_proteins.fasta -out RedCandy_Vcorymbosum_flavonoid_genes_prot_blast.txt #saves all alighments and full output

