#!/bin/bash
#SBATCH --time=12:00:00
#SBATCH --mem=10G
#SBATCH --ntasks=1
#SBATCH --account=rrg-gowens
#SBATCH --cpus-per-task=4
#SBATCH --job-name=Lingonberry_RedCandy_assembly_ragtag_with_Vmac_refgenome
#SBATCH --output=/home/kaedeh/scratch/Lingonberry/log_file/Lingonberry.ragtag.correct.30Nov2022.out
#SBATCH --error=/home/kaedeh/scratch/Lingonberry/log_file/Lingonberry.ragtag.correct.30Nov2022.err

#####################################
### Execution of programs ###########
#####################################

# ---------------------------------------------------------------------
echo "Current working directory: `pwd`"
echo "Starting run at: `date`"
echo "SLURM_JOBID: " $SLURM_JOBID
# ---------------------------------------------------------------------
echo ""

##### Ragtag - reference genome based scaffolding #####

module load StdEnv/2020 minimap2/2.24
source /home/kaedeh/projects/rrg-gowens/kaedeh/Lingonberry/scripts/busco_env/bin/activate

ragtag.py correct \
/home/kaedeh/scratch/Lingonberry/reference_data/V_macrocarpon_Stevens_v1.fasta \
/home/kaedeh/projects/rrg-gowens/kaedeh/Lingonberry/output/assembly/Lingonberry_RedCandy_smartdenovo_asm_4.fasta \
-e /home/kaedeh/scratch/Lingonberry/reference_data/Vmac_refgenome_scaffold_names.txt

ragtag.py scaffold \
/home/kaedeh/scratch/Lingonberry/reference_data/V_macrocarpon_Stevens_v1.fasta \
ragtag_output/ragtag.correct.fasta \
-u -e /home/kaedeh/scratch/Lingonberry/reference_data/Vmac_refgenome_scaffold_names.txt

ragtag.py patch \
ragtag_output/ragtag.scaffold.fasta \
/home/kaedeh/scratch/Lingonberry/reference_data/V_macrocarpon_Stevens_v1.fasta \
-u --aligner 'minimap2' --mm2-params '-x asm10' \
-e /home/kaedeh/scratch/Lingonberry/reference_data/Vmac_refgenome_scaffold_names.txt
